import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "To Do App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} max-w-3xl max-auto my-6 border-2 border-yellow-200 p-6 text-center m-auto bg-Hero-image bg-cover left-200 hfull -webkit-backdrop-filter backdrop-blur`}>{children}</body>
    </html>
  );
}
